<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.3.4" name="tilesheet_grass-bg" tilewidth="16" tileheight="16" tilecount="70" columns="10">
 <image source="../../../../../Downloads/Maytch 16x16 Tilesets-2/tilesheet_grass-bg.png" trans="000000" width="160" height="112"/>
 <tile id="0" type="walkable"/>
 <tile id="1" type="walkable"/>
 <tile id="2" type="walkable"/>
 <tile id="3" type="walkable"/>
 <tile id="4" type="walkable"/>
 <tile id="5" type="walkable"/>
 <tile id="6" type="walkable"/>
 <tile id="7" type="walkable"/>
 <tile id="8" type="walkable"/>
 <tile id="9" type="walkable"/>
 <tile id="10" type="fallable"/>
 <tile id="11" type="fallable"/>
 <tile id="12" type="fallable"/>
 <tile id="13" type="walkable"/>
 <tile id="14" type="fallable"/>
 <tile id="15" type="fallable"/>
 <tile id="16" type="fallable"/>
 <tile id="17" type="fallable"/>
 <tile id="18" type="fallable"/>
 <tile id="19" type="fallable"/>
 <tile id="20" type="fallable"/>
 <tile id="21" type="fallable"/>
 <tile id="22" type="fallable"/>
 <tile id="23" type="walkable"/>
 <tile id="24" type="fallable"/>
 <tile id="25" type="fallable"/>
 <tile id="26" type="fallable"/>
 <tile id="27" type="fallable"/>
 <tile id="28" type="fallable"/>
 <tile id="29" type="fallable"/>
 <tile id="30" type="walkable"/>
 <tile id="31" type="walkable"/>
 <tile id="32" type="walkable"/>
 <tile id="33" type="walkable"/>
 <tile id="34" type="fallable"/>
 <tile id="35" type="fallable"/>
 <tile id="36" type="fallable"/>
 <tile id="37" type="fallable"/>
 <tile id="38" type="fallable"/>
 <tile id="39" type="fallable"/>
 <tile id="40" type="fallable"/>
 <tile id="41" type="fallable"/>
 <tile id="42" type="fallable"/>
 <tile id="43" type="fallable"/>
 <tile id="44" type="fallable"/>
 <tile id="45" type="fallable"/>
 <tile id="46" type="fallable"/>
 <tile id="47" type="fallable"/>
 <tile id="48" type="fallable"/>
 <tile id="49" type="fallable"/>
 <tile id="50" type="fallable"/>
 <tile id="51" type="fallable"/>
 <tile id="52" type="fallable"/>
 <tile id="53" type="fallable"/>
 <tile id="54" type="fallable"/>
 <tile id="55" type="fallable"/>
 <tile id="56" type="fallable"/>
 <tile id="57" type="fallable"/>
 <tile id="58" type="fallable"/>
 <tile id="59" type="fallable"/>
 <tile id="60" type="fallable"/>
 <tile id="61" type="fallable"/>
 <tile id="62" type="fallable"/>
 <tile id="63" type="fallable"/>
</tileset>
