<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.3.4" name="tilesheet_grass" tilewidth="16" tileheight="16" tilecount="224" columns="16">
 <image source="../../../../../Downloads/Maytch 16x16 Tilesets-2/tilesheet_grass.png" trans="000000" width="256" height="224"/>
 <tile id="0" type="walkable"/>
 <tile id="1" type="walkable"/>
 <tile id="2" type="walkable"/>
 <tile id="3" type="walkable"/>
 <tile id="4" type="walkable"/>
 <tile id="5" type="walkable"/>
 <tile id="6" type="walkable"/>
 <tile id="7" type="walkable"/>
 <tile id="8" type="walkable"/>
 <tile id="9" type="walkable"/>
 <tile id="16" type="fallable"/>
 <tile id="17" type="fallable"/>
 <tile id="18" type="fallable"/>
 <tile id="19" type="walkable"/>
 <tile id="20" type="fallable"/>
 <tile id="21" type="fallable"/>
 <tile id="22" type="fallable"/>
 <tile id="23" type="fallable"/>
 <tile id="24" type="fallable"/>
 <tile id="25" type="fallable"/>
 <tile id="32" type="fallable"/>
 <tile id="33" type="fallable"/>
 <tile id="34" type="fallable"/>
 <tile id="35" type="walkable"/>
 <tile id="36" type="fallable"/>
 <tile id="37" type="fallable"/>
 <tile id="38" type="fallable"/>
 <tile id="39" type="fallable"/>
 <tile id="40" type="fallable"/>
 <tile id="41" type="fallable"/>
 <tile id="48" type="walkable"/>
 <tile id="49" type="walkable"/>
 <tile id="50" type="walkable"/>
 <tile id="51" type="block"/>
 <tile id="52" type="fallable"/>
 <tile id="53" type="fallable"/>
 <tile id="54" type="fallable"/>
 <tile id="55" type="fallable"/>
 <tile id="56" type="fallable"/>
 <tile id="57" type="fallable"/>
 <tile id="64" type="fallable"/>
 <tile id="65" type="fallable"/>
 <tile id="66" type="fallable"/>
 <tile id="67" type="fallable"/>
 <tile id="68" type="fallable"/>
 <tile id="69" type="fallable"/>
 <tile id="70" type="fallable"/>
 <tile id="71" type="fallable"/>
 <tile id="72" type="fallable"/>
 <tile id="73" type="fallable"/>
 <tile id="80" type="fallable"/>
 <tile id="81" type="fallable"/>
 <tile id="82" type="fallable"/>
 <tile id="83" type="fallable"/>
 <tile id="84" type="fallable"/>
 <tile id="85" type="fallable"/>
 <tile id="86" type="fallable"/>
 <tile id="87" type="fallable"/>
 <tile id="88" type="fallable"/>
 <tile id="89" type="fallable"/>
 <tile id="96" type="fallable"/>
 <tile id="97" type="fallable"/>
 <tile id="98" type="fallable"/>
 <tile id="99" type="fallable"/>
 <tile id="112" type="walkable"/>
 <tile id="113" type="walkable"/>
 <tile id="114" type="walkable"/>
 <tile id="115" type="walkable"/>
 <tile id="116" type="walkable"/>
 <tile id="117" type="walkable"/>
 <tile id="118" type="walkable"/>
 <tile id="119" type="walkable"/>
 <tile id="120" type="walkable"/>
 <tile id="121" type="walkable"/>
 <tile id="128" type="fallable"/>
 <tile id="129" type="fallable"/>
 <tile id="130" type="fallable"/>
 <tile id="131" type="walkable"/>
 <tile id="132" type="fallable"/>
 <tile id="133" type="fallable"/>
 <tile id="134" type="fallable"/>
 <tile id="135" type="fallable"/>
 <tile id="136" type="fallable"/>
 <tile id="137" type="fallable"/>
 <tile id="144" type="fallable"/>
 <tile id="145" type="fallable"/>
 <tile id="146" type="fallable"/>
 <tile id="147" type="walkable"/>
 <tile id="148" type="fallable"/>
 <tile id="149" type="fallable"/>
 <tile id="150" type="fallable"/>
 <tile id="151" type="fallable"/>
 <tile id="152" type="fallable"/>
 <tile id="153" type="fallable"/>
 <tile id="160" type="walkable"/>
 <tile id="161" type="walkable"/>
 <tile id="162" type="walkable"/>
 <tile id="163" type="walkable"/>
 <tile id="165" type="fallable"/>
 <tile id="167" type="fallable"/>
 <tile id="168" type="fallable"/>
 <tile id="169" type="fallable"/>
 <tile id="176" type="fallable"/>
 <tile id="177" type="fallable"/>
 <tile id="178" type="fallable"/>
 <tile id="179" type="fallable"/>
 <tile id="180" type="fallable"/>
 <tile id="181" type="fallable"/>
 <tile id="182" type="fallable"/>
 <tile id="183" type="fallable"/>
 <tile id="184" type="fallable"/>
 <tile id="185" type="fallable"/>
 <tile id="192" type="fallable"/>
 <tile id="193" type="fallable"/>
 <tile id="194" type="fallable"/>
 <tile id="195" type="fallable"/>
 <tile id="197" type="fallable"/>
 <tile id="199" type="fallable"/>
 <tile id="200" type="fallable"/>
 <tile id="201" type="fallable"/>
 <tile id="208" type="fallable"/>
 <tile id="209" type="fallable"/>
 <tile id="210" type="fallable"/>
 <tile id="211" type="fallable"/>
</tileset>
